name: very_good_chat
description: A very good chat app :)

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Functional programming
  dartz: ^0.9.2
  # Annotations for freezed package
  freezed_annotation: ^0.12.0
  # Annotations for json_serializable package
  json_annotation: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Custom lint rules
  lint: ^1.3.0
  # Runs code generation builds
  build_runner: ^1.10.4
  # Awesome code generator
  freezed: ^0.12.2
  # Code generator for json serializations
  json_serializable: ^3.5.0
  # Mocks for testing
  mockito: ^4.1.3


flutter:
  uses-material-design: true

