name: very_good_chat
description: A very good chat app :)

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Functional programming
  dartz: ^0.9.2
  # Enhanced http client
  dio: ^3.0.10
  # Local database
  sqflite: ^1.3.0
  # Service locator
  get_it: ^5.0.1
  # For injecting dependencies
  injectable: ^1.0.5
  # Google sign in
  google_sign_in: ^4.5.6
  # Cubit
  bloc: ^6.1.0
  # Cubit widgets
  flutter_bloc: ^6.1.0
  # Navigation made simple
  auto_route: ^0.6.9
  # Annotations for freezed package
  freezed_annotation: ^0.12.0
  # Annotations for json_serializable package
  json_annotation: ^3.1.0
  # Better than the print function
  logger: ^0.9.4
  # Picking photos
  photo: ^0.4.8
  # Editing photos
  extended_image: ^1.3.0
  # Encoding photos
  image_editor: ^0.7.3
  # Platform paths
  path_provider: ^1.6.24
  # More icons
  font_awesome_flutter: ^8.10.0
  # More progress indicators
  flutter_spinkit: ^4.1.2+1
  # A better snack bar
  flushbar: ^1.10.4
  # List tiles with sliding actions
  flutter_slidable: ^0.5.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Custom lint rules
  lint: ^1.3.0
  # Code gen for injectable
  injectable_generator: ^1.0.6
  # Code gen for auto route
  auto_route_generator: ^0.6.10
  # Runs code generation builds
  build_runner: ^1.10.4
  # Awesome code generator
  freezed: 0.12.3
  # Code generator for json serializations
  json_serializable: ^3.5.0
  # Mocks for testing
  mockito: ^4.1.3
  # Cubit testing
  bloc_test: ^7.1.0
  # For generating launcher icons
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/vgc.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/

